Add --no-stats option in dtcompact

diff --git a/dtcompact b/dtcompact
--- a/dtcompact
+++ b/dtcompact
@@ -29,6 +29,36 @@ cap () { tput "$1" 2>/dev/null >/dev/null; }
 
 fail () { echo "${R}fail${N}::dt:${B}$1${N}:${H}$2${N}:$3" ; }
 
+help="""usage:
+  command | $0 [options]
+
+  options:
+  	-h, --help                 show this help screen.
+  	-N, --no-color             avoid color output.
+  	-S, --no-stats             avoid stats output.
+"""
+
+OPTIONS=$(getopt -o "hNS" --long \
+	"help,no-color,no-stats" -- "$@")
+
+# Abort if getopt fails to parse arguments in any way.
+if [ $? != 0 ] ; then
+	help >&2 && exit 1
+fi
+
+# Parse command line options.
+eval set -- "$OPTIONS"; dt="$(basename $0)"
+while [[ "$1" = -* ]]; do
+    case "$1" in
+    	-h|--help) echo "$help"; exit 0 ;;
+    	-N|--no-color) opt_N=true ;;
+    	-S|--no-stats) opt_S=true ;;
+        --) shift ; break ;;
+        *) echo "$1" ; echo "help" >&2 && exit 1
+    esac
+    shift
+done
+
 # Define colors if capability is present in tty and if -N option is no
 # present in command line.
 if cap colors && ${opt_N:-true}; then
@@ -63,20 +93,22 @@ if [ ${okay} -gt 0 ] || [ ${fail} -gt 0 ] || [ ${unkn} -gt 0 ]; then
 	printf "\n\n"
 fi
 
-if [ $sums -gt 0 ]; then
-	printf "%-20s%5s\n" "${H}Total:${N}" "${sums}"
-	printf "%-20s%5s     [%4s]\n" "${H}Okay:${N}" "${okay}" "$((okay * 100 / sums))%"
-	printf "%-20s%5s     [%4s]\n" "${H}Fail:${N}" "${fail}" "$((fail * 100 / sums))%"
-	printf "%-20s%5s     [%4s]\n" "${H}Unknown:${N}" "${unkn}" "$((unkn * 100 / sums))%"
+if ! ${opt_S:-false}; then
+	if [ $sums -gt 0 ]; then
+		printf "%-20s%5s\n" "${H}Total:${N}" "${sums}"
+		printf "%-20s%5s     [%4s]\n" "${H}Okay:${N}" "${okay}" "$((okay * 100 / sums))%"
+		printf "%-20s%5s     [%4s]\n" "${H}Fail:${N}" "${fail}" "$((fail * 100 / sums))%"
+		printf "%-20s%5s     [%4s]\n" "${H}Unknown:${N}" "${unkn}" "$((unkn * 100 / sums))%"
 
-	if [ ${fail} -gt 0 ]; then
-		printf "\n%-20s\n" "${H}Failed errors:${N}"
-		for m in "${messages[@]}"; do
-			echo "${m}"
-		done
+		if [ ${fail} -gt 0 ]; then
+			printf "\n%-20s\n" "${H}Failed errors:${N}"
+			for m in "${messages[@]}"; do
+				echo "${m}"
+			done
+		fi
+		echo
+	else
+		printf "%-20s%5s\n" "${H}Total:${N}" "${sums}"
 	fi
-	echo
-else
-	printf "%-20s%5s\n" "${H}Total:${N}" "${sums}"
 fi
 
